spring.application.name=DateOfBirthApp
spring.datasource.url=jdbc:mysql://localhost:3306/dateofbirth
spring.datasource.username=root
spring.datasource.password=Root123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# WhatsApp Cloud API
whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID
whatsapp.access-token=YOUR_ACCESS_TOKEN